# Generated by Django 5.2.17 on 2026-08-04 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand name e.g. "CP Plus"', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL slug e.g. "cp-plus"', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Brand logo image (optional — text badge used when empty)', null=True, upload_to='brands/')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in filter panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name e.g. "Network Camera"', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe slug e.g. "network-camera"', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Category description header banner text')),
                ('icon_class', models.CharField(default='flaticon-camera', help_text='CSS icon class for placeholder e.g. "flaticon-camera"', max_length=50)),
                ('gradient_colors', models.CharField(default='#010c3a, #002d5b', help_text='CSS gradient colors for placeholder e.g. "#010c3a, #002d5b"', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in filter panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_number', models.CharField(blank=True, default='', help_text='Official model number e.g. "CP-UNC-DA41L3C-D-LQ2"', max_length=100)),
                ('name', models.CharField(help_text='Full product title', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from name)', max_length=250, unique=True)),
                ('sub_category_name', models.CharField(blank=True, default='', help_text='Fallback string sub-category name', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Product image (optional — CSS gradient placeholder used when empty)', null=True, upload_to='products/')),
                ('short_description', models.TextField(help_text='Brief description shown on cards and in meta tags')),
                ('services_offered', models.JSONField(default=list, help_text='List of service types: ["Sales", "Installation", "AMC", "Repair"]')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide product without deleting')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in catalog grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Spec name e.g. "Resolution"', max_length=100)),
                ('value', models.CharField(help_text='Spec value e.g. "4MP (2560 x 1440)"', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order for display')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
            options={
                'verbose_name': 'Technical Specification',
                'verbose_name_plural': 'Technical Specifications',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Sub-category name e.g. "4 MP" or "8 Ch."', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe slug e.g. "4-mp"', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
    ]
