# Generated by Django 5.2.17 on 2026-09-03 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inquiry_type', models.CharField(choices=[('society_audit', 'Society Site Audit Request'), ('cctv_calculator', 'CCTV Calculator BOQ Spec'), ('contact', 'General Contact Inquiry'), ('product', 'Product Inquiry')], default='society_audit', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted / Follow-Up'), ('audit_scheduled', 'Site Audit Scheduled'), ('quote_sent', 'Quotation / BOQ Sent'), ('won', 'Order Won / Contract Signed'), ('closed', 'Closed / Lost')], default='new', max_length=20)),
                ('name', models.CharField(help_text='Contact person name', max_length=150)),
                ('phone', models.CharField(help_text='Direct phone or mobile number', max_length=25)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address (optional)', max_length=254)),
                ('designation', models.CharField(blank=True, default='', help_text='e.g. Society Secretary', max_length=100)),
                ('organization', models.CharField(blank=True, default='', help_text='Society or Company name', max_length=200)),
                ('locality', models.CharField(blank=True, default='', help_text='Locality in Thane / Mumbai MMR', max_length=150)),
                ('project_type', models.CharField(blank=True, default='', help_text='e.g. New Turnkey Installation', max_length=100)),
                ('flat_count', models.IntegerField(blank=True, help_text='Total flats or units', null=True)),
                ('wing_count', models.IntegerField(blank=True, help_text='Total wings', null=True)),
                ('preferred_time', models.CharField(blank=True, default='', max_length=100)),
                ('systems_required', models.JSONField(blank=True, default=list, help_text='List of systems e.g. ["CCTV", "Intercom", "AMC"]')),
                ('message', models.TextField(blank=True, default='', help_text='Message text or BOQ summary spec')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes by Sunrise team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Inquiry / Lead',
                'verbose_name_plural': 'Customer Inquiries / Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
