# Generated by Django 5.2.17 on 2026-09-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_inquiry"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "display_order", "-created_at"],
                name="prod_active_order_idx",
            ),
        ),
    ]
